### ISSUE TITLE
Edit mode toggle color

### ISSUE THREAD

**Issue by Nenuial** [dbnschools/moodle-theme_learnr#29]
The toggle in the learnr theme used to turn green when toggled. This no longer seems to be the case in Moodle 4.1. The CSS rule is however still present in the template. Any way to fix it ?

**Comment by Nenuial** [comment]
As a follow up, the following css code in the custom SCSS setting has fixed this issue for me (change the color as desired) :

```css
.custom-control-input:checked ~ .custom-control-label::before {
    color: #fff;
    border-color: #78ff9b!important;
    background-color: #78ff9b !important;
}
```
