### ISSUE TITLE
language font selector link text color is dark when it should be light (and a possible fix)

### ISSUE THREAD

**Issue by bilo1967** [dbnschools/moodle-theme_learnr#35]
When I'm on the unlogged user home page, the language selector link text is dark, even if I choose "Primary color navbar with light font color" as navbarcolor. I'm using brandcolor = #075395.

The problem is because some classes are not styled. A fix is to add the following lines in `scss/learnr/posts.scss` at line 53 (and delete the caches) but I don't add a merge request because I'm not sure this is how the developer wants to fix it:

```scss
.langmenu .dropdown .dropdown-toggle {
    color: #c8c8c8;
}
.langmenu .dropdown .dropdown-toggle:hover {
    background-color: #f8f9fa;
    color: $black;
}
```
Or maybe like this:

```scss
.langmenu .dropdown .dropdown-toggle {
    color: #c8c8c8;
}
.langmenu .dropdown .dropdown-toggle:hover {
    color: $white;
}
```

(plugin v4.2.r7 on Moodle 4.1.2)
